---
- name: download datagrip
  get_url:
    url: "{{ datagrip_url }}"
    dest: "/home/{{ username }}/setup/datagrip.tar.gz"

- name: extract datagrip
  unarchive:
    src: /home/{{ username }}/setup/datagrip.tar.gz
    dest: /home/{{ username }}/setup
    owner: "{{ username }}"

- name: Delete directory
  file: path=/opt/datagrip state=absent

- name: Creates directory
  file: path=/opt/datagrip state=directory

- name: MOVE TO /opt/datagrip
  shell: mv /home/{{ username }}/setup/{{ datagrip_folder_name }}/* /opt/datagrip
  become: yes

- lineinfile: dest=/opt/datagrip/bin/datagrip64.vmoptions line="-javaagent:/home/{{ username }}/soft/LinuxJavaFixes-1.0.0-SNAPSHOT.jar"

- name: Run datagrip
  command: "./datagrip.sh"
  args:
    chdir: "/opt/datagrip/bin"
  become: yes
  become_user: "{{ username }}"
