---
- name: download datagrip
  get_url:
    url: "{{ datagrip_url }}"
    dest: "/home/{{ username }}/setup/datagrip.tar.gz"

- name: extract datagrip
  unarchive:
    src: /home/{{ username }}/setup/datagrip.tar.gz
    dest: /home/{{ username }}/setup
    owner: "{{ username }}"

- name: Delete directory DataGrip
  file: path=/opt/datagrip state=absent

- name: create directory DataGrip
  file:
    path: /opt/datagrip
    state: directory

- name: MOVE TO /opt/datagrip
  shell: cp -r /home/{{ username }}/setup/DataGrip*/* /opt/datagrip
  become: yes

- name: DataGrip folder change ownership
  file:
    path: /opt/datagrip
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: RubyMine fix hotkeys in cyrillic keyboard
  lineinfile:
   dest: /opt/datagrip/bin/datagrip64.vmoptions
   line: -javaagent:/home/{{ username }}/soft/LinuxJavaFixes/LinuxJavaFixes-1.0.0-SNAPSHOT.jar

- name: RubyMine using agent
  lineinfile:
   dest: /opt/datagrip/bin/datagrip64.vmoptions
   line: -javaagent:/home/{{ username }}/soft/jetbrains-agent/jetbrains-agent.jar

- name: Run datagrip
  command: "./datagrip.sh"
  args:
    chdir: "/opt/datagrip/bin"
  become: yes
  become_user: "{{ username }}"
