---
- name: Download Docker (linux container)
  get_url:
    url: "https://get.docker.com"
    validate_certs: no
    dest: "/home/{{ username }}/ansible-ubuntu-desktop/docker.sh"

- name: install Docker from script
  command: "sh docker.sh"
  args:
    chdir: "/home/{{ username }}/ansible-ubuntu-desktop/"
