---
- name: Add Docker’s official GPG key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

- name: Add Docker’s repo
  shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes
    force: true 
