---
- name: install numix theme - add numix ppa
  apt_repository:
    repo: "ppa:numix/ppa"
    state: present
    update_cache: yes

- name: install numix theme - install gtk theme
  apt:
    name: numix-gtk-theme
    update_cache: yes

- name: install numix theme - install gnome tweak tool
  apt:
    name: gnome-tweak-tool
    update_cache: yes

- name: install numix theme - set gtk theme to Numix
  gsettings:
    schema: org.gnome.desktop.interface
    key: gtk-theme
    string: Numix
