---
- name: Add the opera APT key
  apt_key: url=http://deb.opera.com/archive.key

- name: Add opera repo
  apt_repository: repo="deb http://deb.opera.com/opera/ stable non-free" state=present

- name: Install opera
  apt:
    name: opera-stable
    update_cache: yes
    force: true
