---
- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
    - python-psycopg2
  tags: packages

- name: postgresql - add repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: postgresql - add official postgresql repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg  main" state=present

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql-{{pg_version}}
    - postgresql-contrib-{{pg_version}}
    - libpq-dev
    - postgresql-{{pg_version}}-plr
    - postgresql-server-dev-{{pg_version}}
    - postgresql-{{pg_version}}-postgis-{{postgis_version}}
  tags: packages

- name: Install postgresq configuration file.
  copy: src=files/postgresql.conf dest=/etc/postgresql/{{pg_version}}/main/postgresql.conf

- name: Create postgres user
  postgresql_user: name={{ pg_user }} password={{ pg_password }}
  become: true
  become_user: postgres
