---
- name: download rubymine
  get_url:
    url: "{{ rubymine_url }}"
    dest: "/home/{{ username }}/setup/rubymine.tar.gz"

- name: extract rubymine
  unarchive:
    src: /home/{{ username }}/setup/rubymine.tar.gz
    dest: /home/{{ username }}/setup
    owner: "{{ username }}"

- name: Delete directory RubyMine
  file: path=/opt/rubymine state=absent

- name: Create directory RubyMine
  file:
    path: /opt/rubymine
    state: directory

- name: MOVE TO /opt/rubymine
  shell: cp -r /home/{{ username }}/setup/RubyMine*/* /opt/rubymine
  become: yes

- name: RubyMine folder change ownership
  file:
    path: /opt/rubymine
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: RubyMine fix hotkeys in cyrillic keyboard
  lineinfile:
   dest: /opt/rubymine/bin/rubymine64.vmoptions
   line: -javaagent:/home/{{ username }}/soft/LinuxJavaFixes/LinuxJavaFixes-1.0.0-SNAPSHOT.jar

- name: Run rubymine
  command: "./rubymine.sh"
  args:
    chdir: "/opt/rubymine/bin"
  become: yes
  become_user: "{{ username }}"
