---
- name: Disable rdoc
  lineinfile:
    dest: "/home/{{ username }}/.gemrc"
    line: "gem: --no-document"
    create: yes
    owner: "{{ username }}"

- name: Bundler install
  shell: gem install bundler

- name: Bundler configurate
  shell: bash -lc 'bundle config --global --jobs 3'
  become: yes
  become_user: "{{ username }}"

- name: Set Pry config
  copy:
    src: files/pryrc
    dest: /home/{{ username }}/.pryrc
    owner: '{{ username }}'
