---
- name: download rubymine
  get_url:
    url: "{{ rubymine_url }}"
    dest: "/home/{{ username }}/setup/rubymine.tar.gz"

- name: extract rubymine
  unarchive:
    src: /home/{{ username }}/setup/rubymine.tar.gz
    dest: /home/{{ username }}/setup
    owner: "{{ username }}"

- name: Delete directory
  file: path=/opt/rubymine state=absent

- name: create directory
  file:
    path: /opt/rubymine
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: MOVE TO /opt/rubymine
  shell: mv /home/{{ username }}/setup/{{ rubymine_folder_name }}/* /opt/rubymine
  become: yes

- lineinfile: dest=/opt/rubymine/bin/rubymine64.vmoptions line="-javaagent:/home/{{ username }}/soft/LinuxJavaFixes-1.0.0-SNAPSHOT.jar"

- name: Run rubymine
  command: "./rubymine.sh"
  args:
    chdir: "/opt/rubymine/bin"
  become: yes
  become_user: "{{ username }}"
