---
- name: Disable rdoc
  lineinfile:
    dest: "/home/{{ username }}/.gemrc"
    line: "gem: --no-rdoc --no-ri"
    create: yes
    owner: "{{ username }}"

- name: bundler configurate
  shell: "bash -lc 'bundle config --global --jobs 3'"
  become: yes
  become_user: "{{ username }}"

- name: Set Pry config
  copy:
    src: files/pryrc
    dest: /home/{{ username }}/.pryrc
    owner: '{{ username }}'