---
- name: Add Apt Keys sbt
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=2EE0EA64E40A89B84B2DF73499E82A75642AC823 state=present

- name: Add repository sbt
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /'

- name: Install sbt
  apt: name=sbt update_cache=yes
