---
- name: Add Apt Keys (2017-11) Spotify
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0DF731E45CE24F27EEEB1450EFDC8610341D9410 state=present

- name: Add repository Spotify
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: Install Spotify
  apt: name=spotify-client update_cache=yes
