---
- name: Add Sublime Text GPG key
  apt_key:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    state: present

- name: Add Sublime Text repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/

- name: Install Sublime Text
  apt:
    name: sublime-text
    state: present
    update_cache: yes
