---
- name: create Telegram dir
  become: true
  become_method: sudo
  file:
    path: /opt/telegram
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: extract archive to Telegram dir
  become: true
  become_method: sudo
  unarchive:
    src: https://telegram.org/dl/desktop/linux
    dest: /opt/telegram
    owner: "{{ username }}"
    group: "{{ username }}"
    remote_src: true
    validate_certs: false
