---
- name: Install several utilities and monitoring software
  apt:
    name:
      - deja-dup
      - unity-tweak-tool
      - indicator-multiload
      - psensor
      - gparted
      - mpv
      - filezilla
      - p7zip-full
      - htop
      - iotop
      - powertop
      - xclip
      # - terminator
      - linssid
      # - smartmontools
      # - lxc
      # - gv
      # - texlive-lang-cjk
      - memcached
      - pgdbf
      - httpie
      - bat # https://github.com/sharkdp/bat
      - imagemagick

- name: Set date sormat
  shell: "gsettings set com.canonical.indicator.datetime time-format 'custom' && gsettings set com.canonical.indicator.datetime custom-time-format '%a, %d %b %H:%M'"
  become: yes
  become_user: "{{ username }}"
