---
- name: Install VSCode
  include_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: "{{ username }}"
        # code --list-extensions
        visual_studio_code_extensions:
          - EditorConfig.EditorConfig
          - PKief.material-icon-theme
          - vscoss.vscode-ansible
        # cat ~/.config/Code/User/settings.json
        visual_studio_code_settings: {
          "workbench.colorTheme": "Default Light+",
          "workbench.iconTheme": "material-icon-theme",
          "editor.fontSize": 15
        }
