---
# https://yandex.com/support/disk/cli-clients.xml#cli-install
- name: Install Yandex Disk CLI
  shell: 'echo "deb http://repo.yandex.ru/yandex-disk/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/yandex.list > /dev/null && wget http://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG -O- | sudo apt-key add - && sudo apt-get update && sudo apt-get install -y yandex-disk'

# https://github.com/slytomcat/yandex-disk-indicator
- name: Yandex Disk Indicator - add ppa
  apt_repository: repo='ppa:slytomcat/ppa' state=present update_cache=yes

- name: install Yandex Disk Indicator
  apt: name=yd-tools
