---
# https://yandex.com/support/disk/cli-clients.xml#cli-install
- name: Add Yandex Disk GPG
  apt_key:
    url: "http://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG"
    state: present

- name: Add repository Yandex Disk
  apt_repository: repo='deb http://repo.yandex.ru/yandex-disk/deb/ stable main'

- name: Install Yandex Disk
  apt: name=yandex-disk update_cache=yes state=latest

# https://github.com/slytomcat/yandex-disk-indicator
- name: Yandex Disk Indicator - add ppa
  apt_repository: repo='ppa:slytomcat/ppa' state=present update_cache=yes

- name: install Yandex Disk Indicator
  apt: name=yd-tools
