- name: Key
  apt_key: id=86E50310 url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present

- name: Repo
  apt_repository: repo="deb https://dl.yarnpkg.com/debian/ stable main" state=present filename="yarn"

- name: apt-get install yarn
  apt: name=yarn update_cache=yes install_recommends=no state=latest
